### PR TITLE
Updated to work with and without blaze

### PR DESCRIPTION
**Pull request by tmeasday**
Hi Eric,

In preparation to the upcoming blaze release, I made some changes to the package to make it work both with and without the new rendering engine.

### CODE REVIEW

**Comment by tmeasday** [comment]
ping @erobit -- let me know if I can do anything to help out.

**Comment by tmeasday** [comment]
Hey Eric -- 0.8.0 was just released -- wanna release a new version?

**Comment by erobit** [comment]
Hi Tom,

Can you refresh my memory again. Do I simply update the smart.json version #, then mrt release?

Tx.

Eric

**Comment by tmeasday** [comment]
Yes! Exactly that.

**Comment by erobit** [comment]
Tom,

Can’t seem to remember my password, or reset it on the old atmosphere site. Is there a link to the pass reset route?

Eric

**Comment by tmeasday** [comment]
Hey I reset it -- can you email me at tom@thesnail.org and I'll let you know what it is.

**Pull request merged**
