### PR TITLE
Works with 0.6.5

### PR DESCRIPTION
**Pull request by tmeasday**
Did the minimum to get it working with 0.6.5

Probably it needs more of an overhaul, but this seems to work.

Won't with < 0.6.5 with these changes.

### CODE REVIEW

**Comment by tmeasday** [comment]
Fixes #15

**Comment by Goddard** [comment]
awesome

**Comment by tmeasday** [comment]
Any chance of a release? Quite a few people are getting blocked by this as they work through the book..

**Comment by erobit** [comment]
Released.

**Comment by tmeasday** [comment]
Thanks Eric, appreciate it.

**Pull request merged**
